PRE: dt
PORT: 8022
HOST: http://120.24.55.58
AES_KEY: 267a4733f3d89127bac20be290742c81
ADMIN:
  username: 13751198387
  password: 123456

ROUTES:
  - index
  - 
    - user
    - user_detail
    - user_active
  - 
    - device
    - device_detail
    - device_authorize
  - apk
  - firmware
  - alert
  - content
  - message
  - feedback
  - email
  - aboutus
  - question

# 左侧菜单栏, 与 ROUTES 对应
SIDER:
  - 首页
  - 
    - 用户
    - 用户详情
    - 活跃用户
  - 
    - 设备
    - 设备详情
    - 设备授权
  - APK升级
  - 固件升级
  - 告警管理
  - 内容发布
  - 消息管理
  - 用户反馈
  - 邮件管理
  - 关于我们
  - 常见问题
